Repository abhi03ruchi/Anndaata-Connect, pull requests merged in 2025-01, with the labels that each got.

#5 Required changes made
  src/App.js
  src/Components/Banner/HomeBanner.jsx
  src/Components/Footer/Footer.jsx
  src/Components/Navbar/Button.jsx
  src/Pages/Home/Home.css
  src/Pages/Home/Home.jsx
  src/Pages/RegisterAndLoginforNGO/Login.jsx
  src/Pages/RegisterAndLoginforNGO/RegisterAndLogin.css
  src/Pages/RegisterAndLoginforNGO/Registration.jsx
Labels: SWOC, BEGINNER

#13 Fixed home page responsiveness
  src/Components/About/About.css
  src/Components/About/About.jsx
  src/Components/Banner/HomeBanner.jsx
  src/Components/Footer/Footer.jsx
  src/Components/Navbar/Navbar.jsx
  src/Components/SustainableGoals.jsx
  src/Pages/Home/Home.css
  src/Pages/Home/Home.jsx
Labels: SWOC, INTERMEDIATE

#45 updating the scroll button position
  src/Components/GoToTop/GoToTop.css
Labels: SWOC, BEGINNER

#41 Added Registration page for Donors
  src/App.js
  src/Pages/Registerpagefordonors/register.css
  src/Pages/Registerpagefordonors/register.jsx
Labels: SWOC, ADVANCE

#21 Added few animation and styles to the layout issue #10
  package-lock.json
  package.json
  src/Components/About/About.css
  src/Components/Banner/Banner.css
  src/Components/Banner/HomeBanner.jsx
  src/Components/Features/Feature.css
  src/Components/Features/Feature.jsx
  src/Components/Parallax.jsx
  src/Components/Services/OurServices.jsx
  src/Components/Stats/Stats.jsx
  src/Components/SustainableGoals.jsx
  src/Pages/Home/Home.jsx
Labels: SWOC, ADVANCE

#62 Added New Register page for user
  package-lock.json
  package.json
  src/Pages/RegisterAndLoginforNGO/Registration.jsx
  tailwind.config.js
Labels: SWOC, INTERMEDIATE

#98 Fixed Navbar Issues
  src/Components/Navbar/Navbar.css
Labels: SWOC, BEGINNER
